name: Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PHP & Dependencies
        run: |
          sudo apt update
          sudo apt install -y php php-dev php-pear build-essential autoconf libc6-dev

      - name: Build extension
        run: |
          export CFLAGS="-D_GNU_SOURCE"
          phpize
          ./configure --enable-commandutils LDFLAGS="-lregex"
          make
          sudo make install

      - name: Run tests
        run: |
          echo "extension=commandutils.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
          php -m | grep commandutils
